### PR TITLE
Support Scala-Native 0.5.0, bump minimum versions of Scala 2 and Scala 3 accordingly

### PR DESCRIPTION
**Pull request by lihaoyi**
This would be the first step in getting the rest of com.lihaoyi out for scala native 0.5.0

Given the version support drops, which version should we bump here? Would it be the major version (i.e. geny 2.0.0), or a minor version (i.e. geny 1.1.0)? I am inclined to make it a minor version, reflecting the fact that Scala 3.1.3 is not LTS so dropping support is not a huge deal

### CODE REVIEW

**Comment by lihaoyi** [comment]
review by @lolgab @lefou

**Comment by lolgab** [comment]
There is consensus among the Scala Native to not crosscompile but just switch to the new Scala Native version.
Regarding the version, since Scala Native is an experimental target, I would increase the patch version or at most the minor, increasing the major is disruptive the whole ecosystem for no reason since switching native version we are releasing a completely new artifact and stop releasing another one, but the other artifacts are fully compatible with each other

**Comment by lefou** [comment]
I think a minor version bump is fine.

**Comment by lihaoyi** [comment]
Ok, I'll merge this and release it as 1.1.0 then

**Pull request merged**
